### ISSUE TITLE
Paste clipboard text activity 

### ISSUE THREAD

**Issue by sirius16** [clipto-pro/Android#20] opened 2020-02-18 16:48 UTC
With the clipto notification, I can press the paste button and the text is automatically copied. Similar to using the "Clipto..." option, as described here
![Screenshot_20200218_114316](https://user-images.githubusercontent.com/4426180/74757346-dea71600-5243-11ea-9603-b8ef071dd894.png)

What I am proposing is creating an activity that does this as well, an activity that, when activated, instantly creates a note from the clipboard data. 

It would be very helpful as at least a temporary workaround the Android 10 clipboard restriction, as one could use an app like Tasker to detect clipboard changes and automatically create a note

**Comment by atrashler** [comment] 2020-02-18 17:20
By Activity you mean Android Activity (aka visible screen) or something other?
Now I am working on a solution that is implemented in Clip Stack and lets to use the standard ‘Copy’ action after some configuration via adb command.

**Comment by sirius16** [comment] 2020-02-18 17:53
> By Activity you mean Android Activity (aka visible screen) or something other?

Android activity, yes, but not visible. It would run in the background and add the clipboard contents

> Now I am working on a solution that is implemented in Clip Stack and lets to use the standard ‘Copy’ action after some configuration via adb command.

That would be preferable, actually, yeah

**Comment by atrashler** [comment] 2020-02-18 22:20
So I have marked it as duplicate of #11 :)

**Closed as completed** 2020-02-18 22:20 UTC
Labels: duplicate
